#!/usr/bin/env python3

import os
import logging
from pathlib import Path
import argparse

def get_logger() -> logging.Logger:
    logger = logging.getLogger("nvim-config")
    logger.setLevel(logging.INFO)

    formatter = logging.Formatter(
        '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.INFO)
    console_handler.setFormatter(formatter)

    logger.addHandler(console_handler)
    return logger


def set_working_directory(cwd: Path, logger: logging.Logger) -> None:
    cwd = cwd.expanduser().resolve()

    if (not cwd.exists()) or (not cwd.is_dir()):
            raise FileNotFoundError(f"ERROR: 配置文件路径 {cwd} 不存在或不是一个目录")

    check_path: dict[Path, str] = {
        cwd/"init.lua": "缺少 init.lua 文件, 请检查路径是否正确",
        cwd/"lua": "缺少 lua 目录, 请检查路径是否正确",
        cwd/"lua"/"settings": "缺少 settings 目录, 请检查路径是否正确",
    }

    for path, error_msg in check_path.items():
        if not path.exists():
            raise FileNotFoundError(f"ERROR: {error_msg}")

    os.chdir(cwd)
    logger.info(f"配置文件路径: {cwd}")


def get_config_files(cwd: Path) -> dict[str, Path]:
    init_symbols_path = cwd / 'lua' / 'settings' / 'init-symbols'

    return {
        'leader': init_symbols_path/'leader.lua',
        'coleader': init_symbols_path/'coleader.lua',
    }


def write_config_to_file(file_path: Path, content: str) -> None:
    with open(file_path, "w", encoding="utf-8") as file:
        file.write(content)


def sync_config(args: argparse.Namespace, logger: logging.Logger) -> None:
    for key, val in vars(args).items():

        # 跳过命令行传入的配置路径参数(cfg_path)和未设置值的参数
        if key == 'cfg_path' or val is None:
            continue

        cfg_path = get_config_files(args.cfg_path).get(key)

        # 若没有 key 对应的配置路径, 则报错退出
        if not cfg_path:
            logger.critical(f"不支持的配置项: {key}")
            raise NotImplementedError(f"不支持的配置项: {key}")
        # 如果配置文件不存在, 则报错退出
        elif not cfg_path.exists():
            logger.critical(f"配置文件 {cfg_path} 不存在, 请检查路径是否正确")
            raise FileNotFoundError(f"配置文件 {cfg_path} 不存在, 请检查路径是否正确")

        match key :
            case 'leader':
                content = f"_G.Leader = '{val}'\nvim.g.mapleader = _G.Leader"
                write_config_to_file(cfg_path, content)
                msg = f"leader 键已设置为 '{val}'"
                logger.info(f"配置已重置 -- {msg}")

            case 'coleader':
                content = f"_G.CoLeader = '{val}'"
                write_config_to_file(cfg_path, content)
                msg = f"coleader 符号已设置为 '{val}'"
                logger.info(f"配置已重置 -- {msg}")

            case _ :
                logger.critical(f"不支持的配置项: {key}")
                raise NotImplementedError(f"不支持的配置项: {key}")


def get_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="配置 neovim 配置文件的基本参数")
    parser.add_argument( "-c", "--cfg-path", help="设置配置文件路径", type=Path, default=Path(__file__).parent.resolve() )
    parser.add_argument( "--leader", help="设置 leader 键", type=str, default=None )
    parser.add_argument( "--coleader", help="设置 coleader 符号", type=str, default=None )
    return parser.parse_args()


def main() -> None:
    args = get_args()
    logger = get_logger()

    set_working_directory(args.cfg_path, logger)
    sync_config(args, logger)

if __name__ == "__main__":
    main()

